line_length:
  - 150
variable_name:
  excluded:
    - id
    - ip
    - f
disabled_rules:
  - nesting
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
