branches:
 only:
 - master

language: objective-c
osx_image: xcode8
xcode_scheme: Nikka

before_install:
- pod repo remove master
- pod setup

script:
- xcodebuild clean build test -workspace Nikka.xcworkspace -scheme Nikka -destination "name=iPhone 6s"
