branches:
 only:
 - master

language: objective-c
osx_image: xcode8
xcode_scheme: StreemNetworking

before_install:
- pod repo remove master
- pod setup

script:
- xcodebuild clean build test -workspace StreemNetworking.xcworkspace -scheme StreemNetworking -destination "name=iPhone 6s"
