branches:
 only:
 - master

language: objective-c
osx_image: xcode8
xcode_scheme: StreemNetworking

before_install:
- pod repo remove master
- pod setup

script:
- xcodebuild clean build test -project StreemNetworking.xcodeproj -scheme StreemNetworking
