branches:
 only:
 - master

env:
  global:
  - WORKSPACE=Nikka.xcworkspace
  matrix:
    - DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="Nikka-watchOS" SDK="watchsimulator3.0"       RUN_TESTS="NO"
    - DESTINATION="OS=10.0,name=iPhone 6 Plus"     SCHEME="Nikka-iOS"     SDK="iphonesimulator10.0"     RUN_TESTS="NO"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"    SCHEME="Nikka-tvOS"    SDK="appletvsimulator10.0"    RUN_TESTS="NO"
    - DESTINATION="arch=x86_64"                    SCHEME="Nikka-macOS"   SDK="macosx10.12"             RUN_TESTS="NO"

language: objective-c
osx_image: xcode8

before_install:

script:
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild clean test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty;
    else
      xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty;
    fi
