branches:
 only:
 - master

language: objective-c
osx_image: xcode8

before_install:
- pod repo remove master
- pod setup

script:
- xcodebuild clean build test -workspace Nikka.xcworkspace -scheme Nikka-iOS -destination "name=iPhone 6s" ONLY_ACTIVE_ARCH=NO
